import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Sidebar for the main book content
  bookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ros2-humanoid-basics-book',
    },
  ],
};

export default sidebars;
